version: "3"
services:
  ros:
    image: joelimgu/geicar:latest
    ports:
      - 2200:22
    volumes:
      - ./project:/voiture
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/video0:/dev/video0"
    network_mode: host
    restart: always
    entrypoint: voiture/entrypoint.sh

